### ISSUE TITLE
Certain functions hang when input BigDecimal's value is greater than Double's maximum value

### ISSUE THREAD

**Issue by mizlan** [thma/HasBigDecimal#2]
Double's max value is about 1.7976931348623157E+308

In other words, for example if I try to run `fromRational (2 * 10 ^ 308) :: BigDecimal`, it hangs indefinitely. Same goes for quite a few other functions including `roundBD`. Taking a look around the source code, I can't seem to diagnose why. Maybe you'd have some ideas?

**Comment by mizlan** [comment]
```
divideInfo (a, b) (rMode, prefScale) =
  let (BigDecimal numA _, BigDecimal numB _) = matchScales (a, b)
      maxPrecision = fromMaybe (precision a + round (fromInteger (precision b) * 10 / 3)) prefScale
  in (maxPrecision, numA * (10 :: Integer) ^ maxPrecision)
```

```
❯ divideInfo (fromInteger (2 * 10 ^ 307), fromInteger 1) (HALF_UP, Nothing)
(311,2000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000)
❯ divideInfo (fromInteger (2 * 10 ^ 308), fromInteger 1) (HALF_UP, Nothing)
(179769313486231590772930519078902473361797697894230657273430081157732675805500963132708477322407536021120113879871393357658789768814416622492847430639474124377767893424865485276302219601246094119453082952085005768838150682342462881473913110540827237163350510684586298239947245938479716304835356329624224137220,^C^C^C^C^C^C^C^C
```

odd...

**Comment by mizlan** [comment]
The reason is because `precision` function uses `logBase`, which takes in a `Floating a`. But it is bigger than that.

**Comment by thma** [comment]
Thanks for openening this issue!
Do you have an idea for fix? If yes feel free to open a pull request!

**Comment by mizlan** [comment]
Yes! I've actually already forked this and patched it (so I'll create a PR soon), but my way resorts back to dividing by 10 repeatedly. The more efficient alternative would be to bring in the GHC Bignum dependency and use `naturalLogBase`. If you're okay with adding this dependency, let me know because I think this is the nicer solution, and I will change my PR to use that instead. However, I completely understand if you'd like to keep dependency count low, since the dividing-by-10 way isn't terribly slow anyway.

**Comment by thma** [comment]
Hi Michael,

I'm fine with a dependency to GHC Bignum. So please go ahead with your PR!

regards,
Thomas

**Comment by mizlan** [comment]
Nevermind. GHC Bignum is not meant for use with GHC < 9.0 (https://discourse.haskell.org/t/ghc-bignum-is-not-buildable/2295/2). I consider that a deal breaker. However, I have found a faster way of doing the division. Will do some tests and then make a PR afterward.

**Comment by mizlan** [comment]
Another update: `logBase 10` is very unpredictable with numbers that are like `9999...99999999`. Sometimes, instead of having a decimal place like `24.99999999` it will go up into `25.0` which is not good for calculations.

**Comment by thma** [comment]
fixed by https://github.com/thma/HasBigDecimal/pull/3
