### ISSUE TITLE
fromRational and fromRatio should call nf at the end?

### ISSUE THREAD

**Issue by mizlan** [thma/HasBigDecimal#4]
Hi, is there a reason why fromRational and fromRatio do not call nf, while the `a / b` does? Here:

https://github.com/thma/HasBigDecimal/blob/fdea3efcd9d866f88cfd8c1c833c6fdd1b147a02/src/Data/BigDecimal.hs#L112-L119

**Comment by mizlan** [comment]
I believe it is desirable for this to be the case, especially seeing as it constructs a new BigDecimal value. I have updated my fork with this change.

**Comment by thma** [comment]
Hi again Michael,
yes, I think you're right. I guess I just missed it.

I've created a PR from your fork!
