### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by mizlan** [thma/HasBigDecimal#6]
Hi, the API has changed quite significantly. I'm wondering when you'd create a new release on Hackage?

**Comment by thma** [comment]
Yes! I've been preparing this already: incrementing the version number, updating the Readme.

(I was hesitating because I've still not find the time to finish the `Floating` implementation...)

**Comment by thma** [comment]
Done: https://hackage.haskell.org/package/HasBigDecimal-0.2.0.0/docs/Data-BigDecimal.html
